local_costmap:
  global_frame: /robot_odom
  robot_base_frame: /robot_base_footprint
  update_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05

  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0

  plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}